##Basic Numpy

In [34]:
import numpy as np

In [ ]:
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.ones((3,3)) > 0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np.ones((3,3), bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np.full((3,3), True, bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np.arange(0,10)
arr1 = arr%2 == 1
print(arr)
print(arr1)
print(arr[arr1])

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [ ]:
arr = np.arange(0,10)
arr1 = arr%2 == 1
arr[arr1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
arr = np.arange(10)
arr_2d = arr.reshape(2,-1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([arr1,arr2], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
arr = np.array([1 ,2 ,3])
print(np.repeat(arr ,3))
print(np.tile(arr ,3))


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np.vectorize( maxx , otypes =[ float ])
print (pair_max(a , b ))


[6. 7. 9. 8. 9. 7. 5.]


In [3]:
a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print("Result ", np.where(a <b , b , a ))


Result  [6 7 9 8 9 7 5]


##Image Processing

In [4]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 78.9MB/s]


In [24]:
def lightness_func(vector):
    return np.max(vector)*0.5 +np.min(vector)*0.5

def average_func(vector):
    return np.average(vector)

def luminosity_func(vector):
    return vector[0]*0.21 + vector[1]*0.72 + vector[2]*0.07

In [20]:
import matplotlib.image as mpimg
img = mpimg.imread ('/content/dog.jpeg')
gray_img_01 = np.apply_along_axis(lightness_func, axis=2, arr=img)
print(gray_img_01)
print(gray_img_01[0,0])

[[102.5  73.5  66.5 ... 156.  156.  156. ]
 [103.5  73.5  67.5 ... 155.5 156.  155.5]
 [103.5  74.5  67.5 ... 155.  154.5 154. ]
 ...
 [124.5 104.5  97.  ... 117.  114.  112. ]
 [117.5  97.5  90.5 ... 117.  114.  112.5]
 [115.5  95.5  87.5 ... 119.  116.  114.5]]
102.5


In [25]:
gray_img_02 = np.apply_along_axis(average_func, axis=2, arr=img)
print(gray_img_02)
print(gray_img_02[0,0])

[[107.66666667  78.66666667  71.66666667 ... 154.33333333 154.33333333
  154.33333333]
 [108.66666667  78.66666667  72.66666667 ... 154.         154.33333333
  154.        ]
 [108.66666667  79.66666667  72.66666667 ... 153.66666667 153.
  152.66666667]
 ...
 [131.33333333 111.66666667 104.33333333 ... 116.66666667 113.66666667
  111.33333333]
 [124.33333333 104.66666667  97.66666667 ... 116.66666667 113.66666667
  111.66666667]
 [122.33333333 102.66666667  94.66666667 ... 118.33333333 115.33333333
  113.33333333]]
107.66666666666667


In [27]:
gray_img_03 = np.apply_along_axis(luminosity_func, axis=2, arr=img)
print(gray_img_03)
print(gray_img_03[0,0])

[[126.23  97.23  90.23 ... 159.5  159.5  159.5 ]
 [127.23  97.23  91.23 ... 160.08 159.5  160.08]
 [127.23  98.23  91.23 ... 160.01 159.08 159.01]
 ...
 [148.63 129.49 124.37 ... 139.54 136.54 134.33]
 [141.63 122.49 117.44 ... 138.89 135.89 134.4 ]
 [139.63 120.49 114.44 ... 140.03 137.03 135.54]]
126.22999999999999


##Data table Analyst

In [28]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 18.1MB/s]


In [30]:
import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(data)

[[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3  12. ]
 [151.5  41.3  58.5  16.5]
 [180.8  10.8  58.4  17.9]
 [  8.7  48.9  75.    7.2]
 [ 57.5  32.8  23.5  11.8]
 [120.2  19.6  11.6  13.2]
 [  8.6   2.1   1.    4.8]
 [199.8   2.6  21.2  15.6]
 [ 66.1   5.8  24.2  12.6]
 [214.7  24.    4.   17.4]
 [ 23.8  35.1  65.9   9.2]
 [ 97.5   7.6   7.2  13.7]
 [204.1  32.9  46.   19. ]
 [195.4  47.7  52.9  22.4]
 [ 67.8  36.6 114.   12.5]
 [281.4  39.6  55.8  24.4]
 [ 69.2  20.5  18.3  11.3]
 [147.3  23.9  19.1  14.6]
 [218.4  27.7  53.4  18. ]
 [237.4   5.1  23.5  17.5]
 [ 13.2  15.9  49.6   5.6]
 [228.3  16.9  26.2  20.5]
 [ 62.3  12.6  18.3   9.7]
 [262.9   3.5  19.5  17. ]
 [142.9  29.3  12.6  15. ]
 [240.1  16.7  22.9  20.9]
 [248.8  27.1  22.9  18.9]
 [ 70.6  16.   40.8  10.5]
 [292.9  28.3  43.2  21.4]
 [112.9  17.4  38.6  11.9]
 [ 97.2   1.5  30.   13.2]
 [265.6  20.    0.3  17.4]
 [ 95.7   1.4   7.4  11.9]
 [290.7   4.1   8.5  17.8]
 [266.9  43.8   5.   25.4]
 

In [45]:
max = np.max(data[:,3])
print(max)
index = np.argmax(data[:,3])
print(index)

27.0
175


In [48]:
avgTV = np.average(data[:,0])
print(avgTV)

147.0425


In [40]:
index_sales = np.where(data[:,3] >= 20)
print(index_sales[0])
print(len(index_sales[0]))

[  0  15  17  23  27  30  36  39  42  47  52  53  54  55  58  61  62  69
  84  85  93  97  98 101 104 111 113 128 137 139 142 147 154 169 175 176
 183 185 188 198]
40


In [41]:
index_sales = np.where(data[:,3] >= 15)
avg_radio = np.average(data[index_sales,1])
print(avg_radio)

26.22293577981651


In [42]:
avg_news = np.average(data[:,2])
index_news = np.where(data[:, 2] > avg_news)
sum_sales = np.sum(data[index_news,3])
print(sum_sales)

1405.1


In [58]:
sales = data[:, 3]
print(sales[130])
avg_sales = sales.mean()
scores = np.where(sales > avg_sales, 'Good', np.where(sales < avg_sales, 'Bad', 'Average'))
print(scores[7:10])

1.6
['Bad' 'Bad' 'Good']


In [60]:
sales = data[:, 3]
avg_sales = sales.mean()
avg_sub = sales - avg_sales
abs_sub = np.abs(avg_sub)
avg_idx = np.argmin(abs_sub)
sales_avg = sales[avg_idx]
print(sales_avg)
scores = np.where(sales > sales_avg, 'Good', np.where(sales < sales_avg, 'Bad', 'Average'))
print(scores[7:10])

15.2
['Bad' 'Bad' 'Good']
